#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;


namespace CaseXL.Data	
{
	public partial class Exhibit
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _type;
		public virtual string Type 
		{ 
		    get
		    {
		        return this._type;
		    }
		    set
		    {
		        this._type = value;
		    }
		}
		
		private string _source;
		public virtual string Source 
		{ 
		    get
		    {
		        return this._source;
		    }
		    set
		    {
		        this._source = value;
		    }
		}
		
		private string _recepient;
		public virtual string Recepient 
		{ 
		    get
		    {
		        return this._recepient;
		    }
		    set
		    {
		        this._recepient = value;
		    }
		}
		
		private string _name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private int? _caseId;
		public virtual int? CaseId 
		{ 
		    get
		    {
		        return this._caseId;
		    }
		    set
		    {
		        this._caseId = value;
		    }
		}
		
		private string _author;
		public virtual string Author 
		{ 
		    get
		    {
		        return this._author;
		    }
		    set
		    {
		        this._author = value;
		    }
		}
		
		private DateTime? _date;
		public virtual DateTime? Date 
		{ 
		    get
		    {
		        return this._date;
		    }
		    set
		    {
		        this._date = value;
		    }
		}
		
		private int? _type_Id;
		public virtual int? Type_Id 
		{ 
		    get
		    {
		        return this._type_Id;
		    }
		    set
		    {
		        this._type_Id = value;
		    }
		}
		
		private Case _case;
		public virtual Case Case 
		{ 
		    get
		    {
		        return this._case;
		    }
		    set
		    {
		        this._case = value;
		    }
		}
		
		private Exhibits_Type _exhibits_Type;
		public virtual Exhibits_Type Exhibits_Type 
		{ 
		    get
		    {
		        return this._exhibits_Type;
		    }
		    set
		    {
		        this._exhibits_Type = value;
		    }
		}
		
		private IList<Exhibits_Fact> _exhibits_Facts = new List<Exhibits_Fact>();
		public virtual IList<Exhibits_Fact> Exhibits_Facts 
		{ 
		    get
		    {
		        return this._exhibits_Facts;
		    }
		}
		
	}
}
