#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;


namespace CaseXL.Data	
{
	public partial class Fact
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _case_Id;
		public virtual int Case_Id 
		{ 
		    get
		    {
		        return this._case_Id;
		    }
		    set
		    {
		        this._case_Id = value;
		    }
		}
		
		private DateTime? _dte;
		public virtual DateTime? Dte 
		{ 
		    get
		    {
		        return this._dte;
		    }
		    set
		    {
		        this._dte = value;
		    }
		}
		
		private string _description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private int _issue_Id;
		public virtual int Issue_Id 
		{ 
		    get
		    {
		        return this._issue_Id;
		    }
		    set
		    {
		        this._issue_Id = value;
		    }
		}
		
		private string _source;
		public virtual string Source 
		{ 
		    get
		    {
		        return this._source;
		    }
		    set
		    {
		        this._source = value;
		    }
		}
		
		private string _evaluation;
		public virtual string Evaluation 
		{ 
		    get
		    {
		        return this._evaluation;
		    }
		    set
		    {
		        this._evaluation = value;
		    }
		}
		
		private DateTime? _date;
		public virtual DateTime? Date 
		{ 
		    get
		    {
		        return this._date;
		    }
		    set
		    {
		        this._date = value;
		    }
		}
		
		private int? _evaluation_Id;
		public virtual int? Evaluation_Id 
		{ 
		    get
		    {
		        return this._evaluation_Id;
		    }
		    set
		    {
		        this._evaluation_Id = value;
		    }
		}
		
		private Case _case;
		public virtual Case Case 
		{ 
		    get
		    {
		        return this._case;
		    }
		    set
		    {
		        this._case = value;
		    }
		}
		
		private Evaluation _evaluation1;
		public virtual Evaluation Evaluation1 
		{ 
		    get
		    {
		        return this._evaluation1;
		    }
		    set
		    {
		        this._evaluation1 = value;
		    }
		}
		
	}
}
