#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;


namespace CaseXL.Data	
{
	public partial class Issues_Fact
	{
		private int _id;
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int? _case_Id;
		public virtual int? Case_Id 
		{ 
		    get
		    {
		        return this._case_Id;
		    }
		    set
		    {
		        this._case_Id = value;
		    }
		}
		
		private int? _issue_Id;
		public virtual int? Issue_Id 
		{ 
		    get
		    {
		        return this._issue_Id;
		    }
		    set
		    {
		        this._issue_Id = value;
		    }
		}
		
		private int? _fact_Id;
		public virtual int? Fact_Id 
		{ 
		    get
		    {
		        return this._fact_Id;
		    }
		    set
		    {
		        this._fact_Id = value;
		    }
		}
		
		private Issue _issue;
		public virtual Issue Issue 
		{ 
		    get
		    {
		        return this._issue;
		    }
		    set
		    {
		        this._issue = value;
		    }
		}
		
	}
}
