#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;


namespace CaseXL.Data	
{
	public partial class Staff
	{
		private int _iD;
		public virtual int ID 
		{ 
		    get
		    {
		        return this._iD;
		    }
		    set
		    {
		        this._iD = value;
		    }
		}
		
		private string _firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this._firstName;
		    }
		    set
		    {
		        this._firstName = value;
		    }
		}
		
		private string _lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this._lastName;
		    }
		    set
		    {
		        this._lastName = value;
		    }
		}
		
		private int _partner_ID;
		public virtual int Partner_ID 
		{ 
		    get
		    {
		        return this._partner_ID;
		    }
		    set
		    {
		        this._partner_ID = value;
		    }
		}
		
		private int? _case_ID;
		public virtual int? Case_ID 
		{ 
		    get
		    {
		        return this._case_ID;
		    }
		    set
		    {
		        this._case_ID = value;
		    }
		}
		
		private int _firm_ID;
		public virtual int Firm_ID 
		{ 
		    get
		    {
		        return this._firm_ID;
		    }
		    set
		    {
		        this._firm_ID = value;
		    }
		}
		
		private long _dateCreated;
		public virtual long DateCreated 
		{ 
		    get
		    {
		        return this._dateCreated;
		    }
		    set
		    {
		        this._dateCreated = value;
		    }
		}
		
		private Firm _firm;
		public virtual Firm Firm 
		{ 
		    get
		    {
		        return this._firm;
		    }
		    set
		    {
		        this._firm = value;
		    }
		}
		
		private Partner _partner;
		public virtual Partner Partner 
		{ 
		    get
		    {
		        return this._partner;
		    }
		    set
		    {
		        this._partner = value;
		    }
		}
		
		private IList<Case> _cases = new List<Case>();
		public virtual IList<Case> Cases 
		{ 
		    get
		    {
		        return this._cases;
		    }
		}
		
	}
}
