#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Case
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _caption;
		public virtual string Caption
		{
			get
			{
				return this._caption;
			}
			set
			{
				this._caption = value;
			}
		}
		
		private string _case_Number;
		public virtual string Case_Number
		{
			get
			{
				return this._case_Number;
			}
			set
			{
				this._case_Number = value;
			}
		}
		
		private string _firm_Number;
		public virtual string Firm_Number
		{
			get
			{
				return this._firm_Number;
			}
			set
			{
				this._firm_Number = value;
			}
		}
		
		private int? _staff_ID;
		public virtual int? Staff_ID
		{
			get
			{
				return this._staff_ID;
			}
			set
			{
				this._staff_ID = value;
			}
		}
		
		private int _partner_ID;
		public virtual int Partner_ID
		{
			get
			{
				return this._partner_ID;
			}
			set
			{
				this._partner_ID = value;
			}
		}
		
		private int _firm_ID;
		public virtual int Firm_ID
		{
			get
			{
				return this._firm_ID;
			}
			set
			{
				this._firm_ID = value;
			}
		}
		
		private int? _case_Type_ID;
		public virtual int? Case_Type_ID
		{
			get
			{
				return this._case_Type_ID;
			}
			set
			{
				this._case_Type_ID = value;
			}
		}
		
		private Staff _staff;
		public virtual Staff Staff
		{
			get
			{
				return this._staff;
			}
			set
			{
				this._staff = value;
			}
		}
		
		private IList<Exhibit> _exhibits = new List<Exhibit>();
		public virtual IList<Exhibit> Exhibits
		{
			get
			{
				return this._exhibits;
			}
		}
		
		private IList<Exhibits_Fact> _exhibits_Facts = new List<Exhibits_Fact>();
		public virtual IList<Exhibits_Fact> Exhibits_Facts
		{
			get
			{
				return this._exhibits_Facts;
			}
		}
		
		private IList<Fact> _facts = new List<Fact>();
		public virtual IList<Fact> Facts
		{
			get
			{
				return this._facts;
			}
		}
		
	}
}
#pragma warning restore 1591
