#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CaseXL.Data	
{
	public partial class Document
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _doc_Type;
		public virtual int? Doc_Type
		{
			get
			{
				return this._doc_Type;
			}
			set
			{
				this._doc_Type = value;
			}
		}
		
		private string _doc_Name;
		public virtual string Doc_Name
		{
			get
			{
				return this._doc_Name;
			}
			set
			{
				this._doc_Name = value;
			}
		}
		
		private string _doc_Url;
		public virtual string Doc_Url
		{
			get
			{
				return this._doc_Url;
			}
			set
			{
				this._doc_Url = value;
			}
		}
		
		private int? _doc_ParentId;
		public virtual int? Doc_ParentId
		{
			get
			{
				return this._doc_ParentId;
			}
			set
			{
				this._doc_ParentId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
