#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Exhibits_Fact
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _caseId;
		public virtual int? CaseId
		{
			get
			{
				return this._caseId;
			}
			set
			{
				this._caseId = value;
			}
		}
		
		private int? _factId;
		public virtual int? FactId
		{
			get
			{
				return this._factId;
			}
			set
			{
				this._factId = value;
			}
		}
		
		private int? _exhibitId;
		public virtual int? ExhibitId
		{
			get
			{
				return this._exhibitId;
			}
			set
			{
				this._exhibitId = value;
			}
		}
		
		private Exhibit _exhibit;
		public virtual Exhibit Exhibit
		{
			get
			{
				return this._exhibit;
			}
			set
			{
				this._exhibit = value;
			}
		}
		
		private Case _case;
		public virtual Case Case
		{
			get
			{
				return this._case;
			}
			set
			{
				this._case = value;
			}
		}
		
	}
}
#pragma warning restore 1591
