#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Fact_Witness_Question
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _witness_Fact_Id;
		public virtual int Witness_Fact_Id
		{
			get
			{
				return this._witness_Fact_Id;
			}
			set
			{
				this._witness_Fact_Id = value;
			}
		}
		
		private string _question;
		public virtual string Question
		{
			get
			{
				return this._question;
			}
			set
			{
				this._question = value;
			}
		}
		
		private string _answer;
		public virtual string Answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				this._answer = value;
			}
		}
		
		private bool _asked;
		public virtual bool Asked
		{
			get
			{
				return this._asked;
			}
			set
			{
				this._asked = value;
			}
		}
		
		private double? _question_Number;
		public virtual double? Question_Number
		{
			get
			{
				return this._question_Number;
			}
			set
			{
				this._question_Number = value;
			}
		}
		
		private Witness_Fact _witness_Fact;
		public virtual Witness_Fact Witness_Fact
		{
			get
			{
				return this._witness_Fact;
			}
			set
			{
				this._witness_Fact = value;
			}
		}
		
	}
}
#pragma warning restore 1591
