#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Question
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _question1;
		public virtual string Question1
		{
			get
			{
				return this._question1;
			}
			set
			{
				this._question1 = value;
			}
		}
		
		private string _answer;
		public virtual string Answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				this._answer = value;
			}
		}
		
		private int? _witness_Id;
		public virtual int? Witness_Id
		{
			get
			{
				return this._witness_Id;
			}
			set
			{
				this._witness_Id = value;
			}
		}
		
		private Witness _witness;
		public virtual Witness Witness
		{
			get
			{
				return this._witness;
			}
			set
			{
				this._witness = value;
			}
		}
		
	}
}
#pragma warning restore 1591
