#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Witness_Fact
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _caseId;
		public virtual int? CaseId
		{
			get
			{
				return this._caseId;
			}
			set
			{
				this._caseId = value;
			}
		}
		
		private int? _factId;
		public virtual int? FactId
		{
			get
			{
				return this._factId;
			}
			set
			{
				this._factId = value;
			}
		}
		
		private int? _witnessId;
		public virtual int? WitnessId
		{
			get
			{
				return this._witnessId;
			}
			set
			{
				this._witnessId = value;
			}
		}
		
		private Witness _witness;
		public virtual Witness Witness
		{
			get
			{
				return this._witness;
			}
			set
			{
				this._witness = value;
			}
		}
		
		private IList<Fact_Witness_Question> _fact_Witness_Questions = new List<Fact_Witness_Question>();
		public virtual IList<Fact_Witness_Question> Fact_Witness_Questions
		{
			get
			{
				return this._fact_Witness_Questions;
			}
		}
		
	}
}
#pragma warning restore 1591
