#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CaseXL.Data;

namespace CaseXL.Data	
{
	public partial class Witness
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private int? _caseId;
		public virtual int? CaseId
		{
			get
			{
				return this._caseId;
			}
			set
			{
				this._caseId = value;
			}
		}
		
		private string _docs_Received;
		public virtual string Docs_Received
		{
			get
			{
				return this._docs_Received;
			}
			set
			{
				this._docs_Received = value;
			}
		}
		
		private string _docs_Authored;
		public virtual string Docs_Authored
		{
			get
			{
				return this._docs_Authored;
			}
			set
			{
				this._docs_Authored = value;
			}
		}
		
		private IList<Question> _questions = new List<Question>();
		public virtual IList<Question> Questions
		{
			get
			{
				return this._questions;
			}
		}
		
		private IList<Witness_Fact> _witness_Facts = new List<Witness_Fact>();
		public virtual IList<Witness_Fact> Witness_Facts
		{
			get
			{
				return this._witness_Facts;
			}
		}
		
	}
}
#pragma warning restore 1591
